# TODO use .env file for environment variables
version: "3.8"

services:
  parcel_delivery_dev_db:
    container_name: parcel_delivery_dev_db
    image: postgres:13
    environment:
      POSTGRES_USER: stroka01
      POSTGRES_PASSWORD: user
      POSTGRES_DB: dev_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_parcel_delivery_dev_db:/var/lib/postgresql/data
    restart: always

  parcel_delivery_test_db:
    container_name: parcel_delivery_test_db
    image: postgres:13
    environment:
      POSTGRES_USER: stroka01
      POSTGRES_PASSWORD: user
      POSTGRES_DB: test_db
    ports:
      - "8433:5432"
    volumes:
      - pgdata_parcel_delivery_test_db:/var/lib/postgresql/data
    restart: always

  exchange_db:
    container_name: exchange
    image: postgres:13
    environment:
      POSTGRES_USER: stroka01
      POSTGRES_PASSWORD: user
      POSTGRES_DB: exchange_db
    ports:
      - "8434:5432"
    volumes:
      - exchange_db:/var/lib/postgresql/data
    restart: always

  exchange_test_db:
    container_name: exchange_test_db
    image: postgres:13
    environment:
      POSTGRES_USER: stroka01
      POSTGRES_PASSWORD: test
      POSTGRES_DB: exchange_test_db
    ports:
      - "5434:5432"
    volumes:
      - exchange_test_db:/var/lib/postgresql/data
    restart: always

  report_worker_test_db:
    container_name: report_worker
    image: postgres:13
    environment:
      POSTGRES_USER: stroka01
      POSTGRES_PASSWORD: user
      POSTGRES_DB: report_worker_test_db
    ports:
      - "8436:5432"
    volumes:
      - report_worker_test_db:/var/lib/postgresql/data
    restart: always

  il_db:
    container_name: il_db
    image: postgres:13
    environment:
      POSTGRES_USER: stroka01
      POSTGRES_PASSWORD: user
      POSTGRES_DB: il_db
    ports:
      - "8435:5432"
    volumes:
      - il_db:/var/lib/postgresql/data
    restart: always

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--js"

  tracing:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

volumes:
  pgdata_parcel_delivery_dev_db: {}
  pgdata_parcel_delivery_test_db: {}
  exchange_db: {}
  exchange_test_db: {}
  il_db: {}
  cache: {}
  tracing: {}
  report_worker_test_db: {}

networks:
  default:
    name: my_network
    driver: bridge
